#!/usr/bin/env bash
# skill-graph.sh — regenerate skill-graph.md from the skill source directories.
#
# Usage:
#   tools/skill-graph.sh
#   tools/skill-graph.sh --help
#
# Source of truth is plugins/coordinated-skills/skills/<name>/, not any prior
# doc. Any drift between docs and reality gets caught here.

set -euo pipefail

usage() {
  cat <<'EOF'
skill-graph.sh — regenerate skill-graph.md at the repo root.

Usage:
  tools/skill-graph.sh
  tools/skill-graph.sh --help

Reads every skill directory's SKILL.md, parses its frontmatter for
phase + hands_off_to, and writes a Markdown table plus a Mermaid graph
to skill-graph.md.
EOF
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/plugins/coordinated-skills/skills"
OUT="$REPO_ROOT/skill-graph.md"
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

# Phase ordering for the table.
PHASE_ORDER="intake plan execute verify communicate bookend meta"

# Parse each skill into a TSV line: name<TAB>phase<TAB>hands_off_to<TAB>tombstone
ROWS_FILE="$TMP_DIR/rows.tsv"
> "$ROWS_FILE"

for skill_dir in "$SKILLS_DIR"/*/; do
  [[ -d "$skill_dir" ]] || continue
  name=$(basename "$skill_dir")
  skill_md="$skill_dir/SKILL.md"
  if [[ ! -f "$skill_md" ]]; then
    echo "warning: $name has no SKILL.md — skipping" >&2
    continue
  fi

  frontmatter=$(awk '
    /^---[[:space:]]*$/ {
      count++
      if (count == 1) { in_block = 1; next }
      if (count == 2) { exit }
    }
    in_block { print }
  ' "$skill_md")

  phase=$(printf "%s\n" "$frontmatter" | sed -nE 's/^phase:[[:space:]]*([A-Za-z_-]+).*/\1/p' | head -n1)
  # `|| true` so a skill missing the hands_off_to key (no grep match) doesn't abort
  # the whole run under `set -e`/`pipefail`; it falls through to an empty handoff list.
  hot_line=$(printf "%s\n" "$frontmatter" | grep -E "^hands_off_to:" | head -n1 || true)
  hot_inner=$(printf "%s" "$hot_line" | sed -E 's/^hands_off_to:[[:space:]]*\[(.*)\][[:space:]]*$/\1/')
  if [[ "$hot_inner" == "$hot_line" ]]; then
    hot_inner=""
  fi
  # Normalize: trim whitespace, comma-separated
  hot_clean=$(printf "%s" "$hot_inner" | tr -d ' ')

  # Detect tombstone (DEPRECATED in description)
  tomb="no"
  if grep -qE 'DEPRECATED' "$skill_md" 2>/dev/null; then
    tomb="yes"
  fi

  # Use a non-whitespace delimiter (pipe) because IFS=$'\t' collapses
  # consecutive tabs in bash `read`, which mangles empty hands_off_to fields.
  printf "%s|%s|%s|%s\n" "$name" "${phase:-unknown}" "$hot_clean" "$tomb" >> "$ROWS_FILE"
done

# ---------------------------------------------------------------------------
# Build skill-graph.md
# ---------------------------------------------------------------------------
{
  echo "# Skill graph"
  echo
  echo "_Auto-generated by \`tools/skill-graph.sh\` from the skill source directories._"
  echo "_If this drifts from \`COORDINATION-STATUS.md\`, the source wins — update the doc._"
  echo
  echo "## Phase × handoffs"
  echo
  echo "| Skill | phase | hands_off_to | notes |"
  echo "|---|---|---|---|"

  # Sort rows by phase order then skill name.
  for phase in $PHASE_ORDER; do
    while IFS='|' read -r name p hot tomb; do
      [[ "$p" == "$phase" ]] || continue
      if [[ -z "$hot" ]]; then
        hot_display="—"
      else
        hot_display=$(printf "%s" "$hot" | sed 's/,/, /g')
      fi
      note=""
      [[ "$tomb" == "yes" ]] && note="DEPRECATED tombstone"
      printf "| \`%s\` | %s | %s | %s |\n" \
        "$name" "$p" "$hot_display" "$note"
    done < <(sort "$ROWS_FILE")
  done

  # Catch any rows with unknown phase (shouldn't happen if validation passes).
  while IFS='|' read -r name p hot tomb; do
    case " $PHASE_ORDER " in
      *" $p "*) ;;
      *)
        printf "| \`%s\` | **%s** | %s | unknown phase |\n" "$name" "$p" "${hot:-—}"
        ;;
    esac
  done < <(sort "$ROWS_FILE")

  echo
  echo "## Handoff graph"
  echo
  echo '```mermaid'
  echo "graph LR"

  # Group nodes by phase for readability via subgraphs.
  for phase in $PHASE_ORDER; do
    found_any=0
    while IFS='|' read -r name p hot tomb; do
      [[ "$p" == "$phase" ]] || continue
      if [[ $found_any -eq 0 ]]; then
        echo "  subgraph ${phase}"
        found_any=1
      fi
      if [[ "$tomb" == "yes" ]]; then
        echo "    ${name}[\"${name}<br/><i>DEPRECATED</i>\"]"
      else
        echo "    ${name}"
      fi
    done < <(sort "$ROWS_FILE")
    [[ $found_any -eq 1 ]] && echo "  end"
  done

  # Edges
  while IFS='|' read -r name p hot tomb; do
    [[ -z "$hot" ]] && continue
    IFS=',' read -ra targets <<< "$hot"
    for t in "${targets[@]}"; do
      [[ -z "$t" ]] && continue
      echo "  ${name} --> ${t}"
    done
  done < <(sort "$ROWS_FILE")

  echo '```'
  echo
  echo "## Source"
  echo
  echo "Generated $(date '+%Y-%m-%d %H:%M %Z') from $(wc -l < "$ROWS_FILE" | tr -d ' ') skill(s)."
} > "$OUT"

echo "wrote: $OUT"
